import discord
import feedparser
import os
import json
import asyncio
import aiohttp
from bs4 import BeautifulSoup
from discord import app_commands
from discord.ext import commands
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger

# --- CONFIGURATION ---
# Reads FEEDS_CONFIG JSON from Railway variables to handle multiple forums.
FEEDS_CONFIG_JSON = os.getenv("FEEDS_CONFIG", "[]")

try:
    FEEDS_CONFIG = json.loads(FEEDS_CONFIG_JSON)
except json.JSONDecodeError:
    print("Error: Could not parse FEEDS_CONFIG. Make sure it is valid JSON.")
    FEEDS_CONFIG = []

SCHEDULE_HOUR = int(os.getenv("RSS_SCHEDULE_HOUR", "9")) 
SCHEDULE_MINUTE = int(os.getenv("RSS_SCHEDULE_MINUTE", "00"))
GUILD_ID_VAL = os.getenv("GUILD_ID")
MY_GUILD = discord.Object(id=int(GUILD_ID_VAL)) if GUILD_ID_VAL else None

# Initialize Bot
intents = discord.Intents.default()
# The bot instance is named 'colibot' logically.
colibot = commands.Bot(command_prefix="!", intents=intents)
scheduler = AsyncIOScheduler()

async def fetch_and_format_feed(url, limit=5):
    """Parses an RSS feed (XML) for NEW threads (chrono data)."""
    if not url:
        return []
    
    print(f"Fetching RSS: {url}")
    # RSS parsing is synchronous, run in executor to avoid blocking
    loop = asyncio.get_running_loop()
    feed = await loop.run_in_executor(None, feedparser.parse, url)
    
    if not feed.entries:
        print(f"No entries found for {url}")
        return []

    entries = feed.entries[:limit]
    results = []
    for entry in entries:
        results.append((entry.title, entry.link))
    return results

async def fetch_trending_from_html(url, limit=5):
    """
    Scrapes a standard HTML page for trending threads.
    Requires the URL to be a web page already sorted by views/replies.
    Optimized for common forum software (like XenForfo used by The Coli).
    """
    if not url:
        return []

    print(f"Scraping HTML: {url}")
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url, headers=headers) as response:
                if response.status != 200:
                    print(f"Failed to fetch HTML: {response.status}")
                    return []
                html_text = await response.text()
    except Exception as e:
        print(f"Error fetching HTML: {e}")
        return []

    soup = BeautifulSoup(html_text, 'html.parser')
    results = []
    
    # --- XENFORO PARSING LOGIC ---
    # Targets thread titles in XenForo's standard structure
    thread_titles = soup.select(".structItem-title a")

    # Get base URL for relative links
    base_url = "https://" + url.split("/")[2]

    count = 0
    for link_tag in thread_titles:
        if count >= limit:
            break
        
        title = link_tag.get_text(strip=True)
        href = link_tag.get('href')
        
        # Handle relative URLs
        if href and not href.startswith("http"):
            full_link = base_url + href
        else:
            full_link = href

        if title and full_link:
            results.append((title, full_link))
            count += 1
            
    return results

async def send_digest(channel, title, items, color):
    if not items:
        return

    embed = discord.Embed(title=title, color=color)
    description_lines = []
    for i, (item_title, item_link) in enumerate(items, 1):
        description_lines.append(f"**{i}.** [{item_title}]({item_link})")
    
    embed.description = "\n".join(description_lines)
    embed.set_footer(text=f"Generated by ColiBot at {discord.utils.utcnow().strftime('%H:%M UTC')}")
    await channel.send(embed=embed)

async def run_scheduled_updates():
    """Wrapper function for the scheduler."""
    await process_updates("all")

async def process_updates(update_type="all"):
    """Fetches and posts updates for all configured forums."""
    if not FEEDS_CONFIG:
        print("No feeds configured.")
        return

    for forum in FEEDS_CONFIG:
        forum_name = forum.get("name", "Unknown Forum")
        channel_id = forum.get("channel_id")
        new_url = forum.get("new_url")
        popular_url = forum.get("popular_url")

        channel = colibot.get_channel(channel_id)
        if not channel:
            print(f"Warning: Channel ID {channel_id} not found.")
            continue

        # 1. New Threads (RSS/XML)
        if update_type in ["all", "new"] and new_url:
            new_items = await fetch_and_format_feed(new_url, limit=5)
            if new_items:
                await send_digest(channel, f"🆕 New Threads: {forum_name}", new_items, discord.Color.blue())

        # 2. Trending Threads (HTML Scraping)
        if update_type in ["all", "popular"] and popular_url:
            popular_items = await fetch_trending_from_html(popular_url, limit=5)
            if popular_items:
                await send_digest(channel, f"🔥 Trending Threads: {forum_name}", popular_items, discord.Color.red())

# --- SLASH COMMANDS ---
@colibot.tree.command(name="force_new", description="Manually trigger New Threads update across all configured feeds.")
async def force_new(interaction: discord.Interaction):
    await interaction.response.defer(ephemeral=True)
    await process_updates("new")
    await interaction.followup.send("✅ New Threads Update Triggered!")

@colibot.tree.command(name="force_trending", description="Manually trigger Trending Threads update across all configured feeds.")
async def force_trending(interaction: discord.Interaction):
    await interaction.response.defer(ephemeral=True)
    await process_updates("popular")
    await interaction.followup.send("✅ Trending Threads Update Triggered!")

@colibot.event
async def on_ready():
    print(f'ColiBot logged in as {colibot.user}')
    if MY_GUILD:
        try:
            # Sync commands to the specific guild ID
            colibot.tree.copy_global_to(guild=MY_GUILD)
            await colibot.tree.sync(guild=MY_GUILD)
            print(f"Slash commands synced to Guild: {GUILD_ID_VAL}")
        except Exception as e:
            print(f"Error syncing slash commands: {e}")
    
    # Start the scheduled task
    scheduler.add_job(run_scheduled_updates, CronTrigger(hour=SCHEDULE_HOUR, minute=SCHEDULE_MINUTE))
    scheduler.start()

if __name__ == "__main__":
    token = os.getenv("DISCORD_TOKEN")
    if token:
        colibot.run(token)
    else:
        print("Error: DISCORD_TOKEN environment variable missing.")
